# Use the Default Linux Universal image
FROM mcr.microsoft.com/devcontainers/universal:2

# Install Vue CLI globally (frontend)
RUN npm install -g @vue/cli

# Install Flask via pip (backend)
RUN pip install flask

# Default working directory
WORKDIR /workspace
